### ISSUE TITLE
Meeting links

### ISSUE THREAD

**Issue by MayaGans** [r4ds/bookclub-Advanced_R#18]
- Add a blurb in README that meetings are recorded and can be found as links to the chapters. 
- Add Chapter 2 link:

[Chapter 2](https://notredame.zoom.us/rec/play/vJMrI736p243Hdyd4QSDA_F9W9W_fK-sgCcb8_BcmBuwVHAAZlCgZLYRY7Y1AvOgtjkXt_XVqxb7L8gN?startTime=1587081259000&_x_zm_rtaid=jajmejq0QL-h8W6eszmi3A.1587475558334.cc3864032bcb37a1b8e8a15f063df159&_x_zm_rhtaid=597)

Now sure where we should store these in the long run? May need to change URLs?

**Comment by tanho63** [comment]
Hmmm...I can imagine that zoom storage is not permanent. Could probably back this up to a...youtube account, I suppose?

**Comment by tanho63** [comment]
Also, that link is Chapter 3 ;)

**Comment by MayaGans** [comment]
Closed with PR #19
