### ISSUE TITLE
Restructure/review Q&A 

### ISSUE THREAD

**Issue by tanho63** [r4ds/bookclub-Advanced_R#190]
Collapsing all of the other single-chapter issues into one umbrella issue related to the Q/A: how should this be formatted to make it easier to add to going forward? 

Some considerations:
- How do learning objectives for each chapter fit in?
- Are we talking about developing our own "questions that test whether you've learned what the chapter was talking about" and doing like "hidden answers"?
- (further to the above is "guiding questions" as cohort 2 started with)
- How do we make it easy for new cohorts to add their questions (safely assuming less bookdown experience/desire)?

**Comment by tanho63** [comment]
Also tagging @kevin-m-kent because of past interest in "learning objectives" and "guiding questions" 😎

**Comment by jonthegeek** [comment]
I'm on it. During work hours soon 'cuz I actually have a personal development goal directly related to this. Thanks for assigning me an issue to make it formal!
