### ISSUE TITLE
Checking in on missing slides and/or videos :)

### ISSUE THREAD

**Issue by tanho63** [r4ds/bookclub-Advanced_R#199]
Hey gang! Just starting an issue to help keep the repo updated with slides, videos, and upcoming presentations :) 

Cohort 2
- [ ] @mjeziorski Ch4 slides
- [ ] @eknackstedt Ch5 slides
- [x] Ch3 video (@kevin-m-kent ?)
- [x] Ch6 slides @meenakshi-kushwaha 
- [x] Ch7 slides @kevin-m-kent (?)
- [ ] Ch 10 slides (Jorge Mendes?)
- [ ] Ch 11 slides/video (?)

Cohort 3
- [x] Ch7 slides @aleighbrown 
- [x] Ch 8 slides/video @Shelmith-Kariuki 

Let me know if I can help at all, or if I'm tagging the wrong person, or if the presentation in question hasn't happened yet etc!

**Comment by kevin-m-kent** [comment]
slides were added this morning for my week and video links are up to date for cohort 2

**Comment by Shelmith-Kariuki** [comment]
Hi ... I will upload Chapter 8 slides by end of day today. @aleighbrown handled the video part (I guess?)

**Comment by tanho63** [comment]
Hey @Shelmith-Kariuki  :) Just checking back in on this!

**Comment by Shelmith-Kariuki** [comment]
Hi,

Sorry for the delay. I have submitted a PR regarding the same.
https://shelkariuki.netlify.app/

**Comment by tanho63** [comment]
Closing issue and opening separate issues for each missing, that way we can tag and close on PRs
