### ISSUE TITLE
Definitions ...

### ISSUE THREAD

**Issue by jimrothstein** [r4ds/bookclub-Advanced_R#49]
**Companion Chapter 7
7.2.3**  

Still behind you guys .... and trying to identify all the kinds of `environments`.

**Now:**
> The global environment is your working enviornment...

**Suggest:**
_Global environment_ is where all interactive work is done, except for functions (source: text)
Typical R will construct several environments, or data structures to R.   Beginning with Global Environment R adds one environment level for each added package back to base and the chain ends with  an empty environment.    In this arrangement each environment has one (ONLY - check?) parent  and all are tied together in a _<proper computer science word>_ similar to lists.  As we will see, functions also contribute  environments in this structure.

So what is the _working environment_?

**Comment by MayaGans** [comment]
Closed with PR #50

**Comment by jimrothstein** [comment]
Just my 2 cents:
Remove:
The working environment is the environment whose names would currently mask names in any other environment. Note that in the book, the term current environment is used not working environment.

**Comment by MayaGans** [comment]
@jimrothstein can you provide this edit as a please

**Comment by tanho63** [comment]
Looks like issue was resolved - closing.
