### ISSUE TITLE
Chapter 7.2.3 - Parents  - More Definitions

### ISSUE THREAD

**Issue by jimrothstein** [r4ds/bookclub-Advanced_R#51]
If I  am the one who finds environments ambiguous -- then disregard.
**NOW**
Clarification: the global environment’s parent is all the packages loaded within the environment, not the empty environment, right? How do we check this? parent.env(global)?

Each package becomes a parent to the global environment. We can inspect local enviornments using

Comment:
Think I know what you are saying,   but we make it clearer:
(1) I thought global environment's parent was the last package USER happened to load.  Think you are referring to hierarchy.   Like mother, grandmother, great-grandmother ....  they may all be MOTHERS, but they are not all MY mother:  there is a structure.   For packages, like human generations, it is sequential.

**Comment by tanho63** [comment]
Hi Jim - I think the majority of the discussions and activity are on slack (and transcribed here for archiving purposes among others). Can you open a discussion there?

**Comment by MayaGans** [comment]
I like this disambiguation @jimrothstein but I think it'd be easier if you submitted this as a pull request so we can merge in your suggestions. I tried adding them myself but I'm not quite sure where exactly you're suggesting we add this. Does that make sense?

**Comment by jimrothstein** [comment]
@tanho63, @MayaGans  I will clone, make suggested changes and submit a pull request.    If it is for something I want to ask about, and not suggest changes,  should I post those questions on slack?

**Comment by tanho63** [comment]
Yup, that sums up pretty nicely. I'm not sure how many people are actively receiving notifications any time an issue or PR is opened here, but I do know ~100 people are subscribed to the advR channel and so you'll get much more of a discussion on there than here :)

**Comment by tanho63** [comment]
Looks like discussion was had in Slack and comments appended to repo QA. Closing :)
