### ISSUE TITLE
Chapter 10 - link to Slides not right.

### ISSUE THREAD

**Issue by jimrothstein** [r4ds/bookclub-Advanced_R#66]
On **README.md**  under **Schedule**,  link to **Chapter 10 slides** points to wrong chapter.

**NOW**
2020-06-04 Chapter 10 - Function factories: Jon Harmon (Slides | Zoom Recording)
https://r4ds.github.io/bookclub-Advanced_R/Presentations/Week08/Chapter8.html#1

Thx.

**Comment by tanho63** [comment]
Drat, looks like I did a bad job of pasta!
